---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Values.namespace }}
spec:
  ports:
    - port: {{ .Values.ports.port }}
      targetPort: {{ .Values.ports.targetPort }}
      name: {{ .Values.ports.name }}
      protocol: TCP
  type: NodePort
  selector:
    app: {{ .Chart.Name }}
  
