---
replicas: "1"
namespace: "wordpress"
image:
  repository: "mysql"
  tag: "5.6"
resources:
  requests: 
    cpu: "250m"
    memory: "1Gi"
  limits:
    cpu: "1"
    memory: "2Gi"
ports:
  port: 3306
  targetPort: 3306
  name: mysql
