---
apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: wordpress
  name: wordpress-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/wordpress/files"

---
apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: wordpress
  name: mysql-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/wordpress/data"

